import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit, Lora } from "next/font/google";
import "./globals.css";
import { cn } from "@/shared/lib/utils";
import { Header } from "@/shared/components/layouts/header";
import { AuthStoreProvider } from "@/features/auth/store/auth-store-provider";
import { CartStoreProvider } from "@/features/cart/store/cart-store-provider";
import { Toaster } from "sonner";

const loraHeading = Lora({subsets:['latin'],variable:'--font-heading'});

const outfit = Outfit({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", outfit.variable, loraHeading.variable)}
    >
      <body suppressHydrationWarning className="min-h-full flex flex-col">
        <AuthStoreProvider>
          <CartStoreProvider>
            <Header />
            {children}
            <Toaster richColors position="top-right" />
          </CartStoreProvider>
        </AuthStoreProvider>
      </body>
    </html>
  );
}
